Repository KinsonDigital/VersionMiner, pull requests merged in 2023-02, with the labels that each got.

#84 🚧Fix branch invalid and logging issue
  .github/workflows/build-status-check.yml
  .github/workflows/unit-tests-status-check.yml
  .run/InvalidBranch.run.xml
  README.md
  Testing/VersionMinerTests/GitHubActionTests.cs
  Testing/VersionMinerTests/Models/RepoModelTests.cs
  VersionMiner.sln
  VersionMiner/ExtensionMethods.cs
  VersionMiner/GitHubAction.cs
  VersionMiner/Services/GitHubConsoleService.cs
Labels: 🐛bug, high priority, preview

#85 🚧Create release pipeline
  .config/dotnet-tools.json
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-tests-status-check.yml
  .gitignore
  .nuke/parameters.json
  .vscode/settings.json
  Testing/VersionMinerIntegrationTests/IntegrationTests.cs
  Testing/VersionMinerTests/ExtensionMethodTests.cs
  Testing/VersionMinerTests/Helpers/TestDataLoader.cs
  VersionMiner.sln
  VersionMiner/ExtensionMethods.cs
Labels: medium priority, preview, workflow

#87 🚧Setup code coverage with badge
  .github/workflows/prev-release.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .vscode/settings.json
  Documentation/Images/twitter-logo-16x16.svg
  README.md
  Testing/VersionMinerTests/Exceptions/HeaderAlreadyExistsExceptionTests.cs
  VersionMiner.sln
  VersionMiner/ExtensionMethods.cs
  codecov.yml
Labels: medium priority, preview, 📝documentation/product

#90 🚧Move internal visible setup
  .github/workflows/unit-test-pr-status-check.yml
  VersionMiner/Program.cs
  VersionMiner/VersionMiner.csproj
Labels: low priority, preview, tech debt

#91 🚧Update dotnet version to latest
  Testing/VersionMinerIntegrationTests/VersionMinerIntegrationTests.csproj
  Testing/VersionMinerTests/VersionMinerTests.csproj
  VersionMiner/VersionMiner.csproj
Labels: high priority, preview, dependency update

#92 🚧Update workflows to use env files
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  VersionMiner.sln
Labels: high priority, preview, workflow

#95 🚧Update the actions output
  Dockerfile
  Testing/VersionMinerIntegrationTests/IntegrationTests.cs
  Testing/VersionMinerTests/Services/ActionOutputServiceTests.cs
  Testing/VersionMinerTests/VersionMinerTests.csproj
  VersionMiner/Program.cs
  VersionMiner/Services/ActionOutputService.cs
  VersionMiner/Services/EnvVarService.cs
  VersionMiner/Services/IEnvVarService.cs
  VersionMiner/VersionMiner.csproj
Labels: high priority, preview, tech debt, dependency update

#96 🚧Setup dependabot
  .github/dependabot.yml
Labels: medium priority, preview, workflow

#98 Revert "🚧Improve repo file data service"
  .run/AllInputs.run.xml
  .run/CaseSensistiveFalse.run.xml
  .run/CaseSensistiveMissing.run.xml
  .run/Debug.run.xml
  .run/InvalidBranch.run.xml
  .run/KeyValueMismatchFalse.run.xml
  .run/KeyValueMismatchMissing.run.xml
  .run/WithFakeAuthToken.run.xml
  Testing/VersionMinerIntegrationTests/IntegrationTests.cs
  Testing/VersionMinerIntegrationTests/IntegrationTestsBase.cs
  Testing/VersionMinerTests/GitHubActionTests.cs
  Testing/VersionMinerTests/Services/RepoFileDataServiceTests.cs
  VersionMiner/GitHubAction.cs
  VersionMiner/Program.cs
  VersionMiner/Services/IRepoFileDataService.cs
  VersionMiner/Services/RepoFileDataService.cs
Labels: medium priority, preview, tech debt

#100 🚧Improve repo file data service
  .run/AllInputs.run.xml
  .run/CaseSensistiveFalse.run.xml
  .run/CaseSensistiveMissing.run.xml
  .run/Debug.run.xml
  .run/InvalidBranch.run.xml
  .run/KeyValueMismatchFalse.run.xml
  .run/KeyValueMismatchMissing.run.xml
  .run/WithFakeAuthToken.run.xml
  Testing/VersionMinerIntegrationTests/IntegrationTests.cs
  Testing/VersionMinerIntegrationTests/IntegrationTestsBase.cs
  Testing/VersionMinerTests/DeserializedHttpResponseTests.cs
  Testing/VersionMinerTests/GitHubActionTests.cs
  Testing/VersionMinerTests/HttpResponseTests.cs
  Testing/VersionMinerTests/Services/RepoFileDataServiceTests.cs
  VersionMiner/DeserializedHttpResponse.cs
  VersionMiner/GitHubAction.cs
  VersionMiner/HttpResponse.cs
  VersionMiner/Program.cs
  VersionMiner/Services/HttpClient.cs
  VersionMiner/Services/IHttpClient.cs
  VersionMiner/Services/IRepoFileDataService.cs
  VersionMiner/Services/RepoFileDataService.cs
Labels: medium priority, preview, tech debt

#110 🚧Remove repo related docs
  Documentation/Branching.md
  Documentation/Images/BranchingDiagram-DarkMode-v1.1.png
  Documentation/Images/BranchingDiagram-LightMode-v1.1.png
  code_of_conduct.md
Labels: medium priority, preview, 📝documentation/product

#112 🚧Add .md to LICENSE file
  LICENSE.md
Labels: low priority, preview, 📝documentation/product
