Repository KinsonDigital/VersionMiner, pull requests merged in 2023-08, with the labels that each got.

#156 🚧Adjust release workflow input
  .github/workflows/release.yml
Labels: low priority, ♻️cicd

#158 🚧Lock version of MOQ
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/unit-test-status-check.yml
  README.md
  Testing/VersionMinerTests/VersionMinerTests.csproj
Labels: high priority, 📦dependency update

#161 🚧Adjust workflow trigger
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: high priority, ♻️cicd
