Repository KinsonDigital/VersionMiner, pull requests merged in 2023-11, with the labels that each got.

#163 🚧Update sync workflow
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: medium priority, ♻️cicd

#183 🚧Update to dotnet 8
  Dockerfile
  Testing/VersionMinerIntegrationTests/ExtensionMethods.cs
  Testing/VersionMinerIntegrationTests/VersionMinerIntegrationTests.csproj
  Testing/VersionMinerTests/Helpers/ExtensionMethodsForTesting.cs
  Testing/VersionMinerTests/VersionMinerTests.csproj
  VersionMiner/VersionMiner.csproj
Labels: high priority, preview, 📦dependency update

#182 🚧Remove the newtonsoft package
  Testing/VersionMinerTests/TestData/ProjFileTestSample.csproj
Labels: low priority, 📦dependency update
