Repository KinsonDigital/VersionMiner, pull requests merged in 2023-03, with the labels that each got.

#114 🚧Update twitter link
  Documentation/Images/twitter-logo-16x16.svg
  README.md
Labels: medium priority, preview, 📝documentation/product

#124 🚧Update codecov YML file
  codecov.yml
Labels: high priority, preview, ♻️cicd

#132 🚧Update Readme
  README.md
Labels: high priority, preview, 📝documentation/product

#133 🚀Preview Release
  .config/dotnet-tools.json
  .github/dependabot.yml
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-testing-status-check.yml
  .nuke/parameters.json
  .vscode/release-notes.code-snippets
  Documentation/Branching.md
  Documentation/Images/BranchingDiagram-DarkMode-v1.1.png
  Documentation/Images/BranchingDiagram-LightMode-v1.1.png
  Documentation/Images/twitter-logo-16x16.svg
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  LICENSE.md
  README.md
  Testing/VersionMinerIntegrationTests/VersionMinerIntegrationTests.csproj
  Testing/VersionMinerTests/VersionMinerTests.csproj
  VersionMiner/VersionMiner.csproj
  code_of_conduct.md
  codecov.yml
Labels: 🚀Preview Release

#137 🚧Update contributor covenant badge
  README.md
Labels: high priority, preview, 📝documentation/product
