Repository KinsonDigital/VersionMiner, pull requests merged in 2023-07, with the labels that each got.

#151 🚧Fix README badges
  README.md
Labels: low priority, preview, 📝documentation/product

#152 🚧Improve release workflow
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-testing-status-check.yml
  README.md
Labels: medium priority, ♻️cicd

#154 🚧Perform various improvements
  .editorconfig
  .github/cicd/ChalkColor.ts
  .github/cicd/RunnerService.ts
  .github/cicd/validate-notes.ts
  .github/cicd/validate-tag.ts
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
  .github/workflows/unit-testing-status-check.yml
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/workflow.code-snippets
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/Production-Release-Notes-TEMPLATE.md
  README.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.1.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.3.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  ReleaseNotes/ProductionReleases/Release-Notes-v1.0.0.md
  Testing/.editorconfig
  VersionMiner.sln
  renovate.json
Labels: high priority, 📝documentation/product, ♻️cicd, ⚙️config
